/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextDetectionRouteImport } from './routes/text-detection'
import { Route as ApiPremiumTextRouteImport } from './routes/api/premium-text'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsNewRouteImport } from './routes/investigations.new'
import { Route as InvestigationsIdIndexRouteImport } from './routes/investigations.$id.index'
import { Route as InvestigationsIdAnalysisRouteImport } from './routes/investigations.$id.analysis'
import { Route as InvestigationsIdHeatmapRouteImport } from './routes/investigations.$id.heatmap'
import { Route as InvestigationsIdReportRouteImport } from './routes/investigations.$id.report'
import { Route as InvestigationsIdUploadRouteImport } from './routes/investigations.$id.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextDetectionRoute = TextDetectionRouteImport.update({
  id: '/text-detection',
  path: '/text-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPremiumTextRoute = ApiPremiumTextRouteImport.update({
  id: '/api/premium-text',
  path: '/api/premium-text',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsNewRoute = InvestigationsNewRouteImport.update({
  id: '/investigations/new',
  path: '/investigations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdIndexRoute = InvestigationsIdIndexRouteImport.update({
  id: '/investigations/$id/',
  path: '/investigations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdAnalysisRoute =
  InvestigationsIdAnalysisRouteImport.update({
    id: '/investigations/$id/analysis',
    path: '/investigations/$id/analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestigationsIdHeatmapRoute = InvestigationsIdHeatmapRouteImport.update({
  id: '/investigations/$id/heatmap',
  path: '/investigations/$id/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdReportRoute = InvestigationsIdReportRouteImport.update({
  id: '/investigations/$id/report',
  path: '/investigations/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdUploadRoute = InvestigationsIdUploadRouteImport.update({
  id: '/investigations/$id/upload',
  path: '/investigations/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/text-detection': typeof TextDetectionRoute
  '/api/premium-text': typeof ApiPremiumTextRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/investigations/$id/analysis': typeof InvestigationsIdAnalysisRoute
  '/investigations/$id/heatmap': typeof InvestigationsIdHeatmapRoute
  '/investigations/$id/report': typeof InvestigationsIdReportRoute
  '/investigations/$id/upload': typeof InvestigationsIdUploadRoute
  '/investigations/$id/': typeof InvestigationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/text-detection': typeof TextDetectionRoute
  '/api/premium-text': typeof ApiPremiumTextRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/investigations/$id/analysis': typeof InvestigationsIdAnalysisRoute
  '/investigations/$id/heatmap': typeof InvestigationsIdHeatmapRoute
  '/investigations/$id/report': typeof InvestigationsIdReportRoute
  '/investigations/$id/upload': typeof InvestigationsIdUploadRoute
  '/investigations/$id': typeof InvestigationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/text-detection': typeof TextDetectionRoute
  '/api/premium-text': typeof ApiPremiumTextRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/investigations/$id/analysis': typeof InvestigationsIdAnalysisRoute
  '/investigations/$id/heatmap': typeof InvestigationsIdHeatmapRoute
  '/investigations/$id/report': typeof InvestigationsIdReportRoute
  '/investigations/$id/upload': typeof InvestigationsIdUploadRoute
  '/investigations/$id/': typeof InvestigationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/text-detection'
    | '/api/premium-text'
    | '/investigations/new'
    | '/investigations/'
    | '/investigations/$id/analysis'
    | '/investigations/$id/heatmap'
    | '/investigations/$id/report'
    | '/investigations/$id/upload'
    | '/investigations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/text-detection'
    | '/api/premium-text'
    | '/investigations/new'
    | '/investigations'
    | '/investigations/$id/analysis'
    | '/investigations/$id/heatmap'
    | '/investigations/$id/report'
    | '/investigations/$id/upload'
    | '/investigations/$id'
  id:
    | '__root__'
    | '/'
    | '/text-detection'
    | '/api/premium-text'
    | '/investigations/new'
    | '/investigations/'
    | '/investigations/$id/analysis'
    | '/investigations/$id/heatmap'
    | '/investigations/$id/report'
    | '/investigations/$id/upload'
    | '/investigations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextDetectionRoute: typeof TextDetectionRoute
  ApiPremiumTextRoute: typeof ApiPremiumTextRoute
  InvestigationsNewRoute: typeof InvestigationsNewRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  InvestigationsIdAnalysisRoute: typeof InvestigationsIdAnalysisRoute
  InvestigationsIdHeatmapRoute: typeof InvestigationsIdHeatmapRoute
  InvestigationsIdReportRoute: typeof InvestigationsIdReportRoute
  InvestigationsIdUploadRoute: typeof InvestigationsIdUploadRoute
  InvestigationsIdIndexRoute: typeof InvestigationsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-detection': {
      id: '/text-detection'
      path: '/text-detection'
      fullPath: '/text-detection'
      preLoaderRoute: typeof TextDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/premium-text': {
      id: '/api/premium-text'
      path: '/api/premium-text'
      fullPath: '/api/premium-text'
      preLoaderRoute: typeof ApiPremiumTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/new': {
      id: '/investigations/new'
      path: '/investigations/new'
      fullPath: '/investigations/new'
      preLoaderRoute: typeof InvestigationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/': {
      id: '/investigations/$id/'
      path: '/investigations/$id'
      fullPath: '/investigations/$id/'
      preLoaderRoute: typeof InvestigationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/analysis': {
      id: '/investigations/$id/analysis'
      path: '/investigations/$id/analysis'
      fullPath: '/investigations/$id/analysis'
      preLoaderRoute: typeof InvestigationsIdAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/heatmap': {
      id: '/investigations/$id/heatmap'
      path: '/investigations/$id/heatmap'
      fullPath: '/investigations/$id/heatmap'
      preLoaderRoute: typeof InvestigationsIdHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/report': {
      id: '/investigations/$id/report'
      path: '/investigations/$id/report'
      fullPath: '/investigations/$id/report'
      preLoaderRoute: typeof InvestigationsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/upload': {
      id: '/investigations/$id/upload'
      path: '/investigations/$id/upload'
      fullPath: '/investigations/$id/upload'
      preLoaderRoute: typeof InvestigationsIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextDetectionRoute: TextDetectionRoute,
  ApiPremiumTextRoute: ApiPremiumTextRoute,
  InvestigationsNewRoute: InvestigationsNewRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  InvestigationsIdAnalysisRoute: InvestigationsIdAnalysisRoute,
  InvestigationsIdHeatmapRoute: InvestigationsIdHeatmapRoute,
  InvestigationsIdReportRoute: InvestigationsIdReportRoute,
  InvestigationsIdUploadRoute: InvestigationsIdUploadRoute,
  InvestigationsIdIndexRoute: InvestigationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
